#!/usr/bin/docker build --pull -t trinventum-db -f Dockerfile-trinventum-db .
#
# Trinventum Docker configuration - database container
#
# Copyright (C) 2024-2026 Bogdan 'bogdro' Drozdowski, bogdro (at) users . sourceforge . net
#
# This file is part of Trinventum (Transaction and Inventory Unified Manager),
#  a software that helps manage an e-commerce business.
# Trinventum homepage: https://trinventum.sourceforge.io/
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# https://docs.docker.com/engine/reference/builder/

# https://hub.docker.com/_/postgres
FROM postgres:16

######################################################################
# NOTE: for professional use, you MUST add a permanent storage
######################################################################

RUN mkdir /docker-entrypoint-initdb.d || true
COPY docker/docker-db-create.sh /docker-entrypoint-initdb.d/
RUN chmod a+rx /docker-entrypoint-initdb.d/docker-db-create.sh
USER postgres

# "$POSTGRES_USER"?
#RUN su - postgres -c "echo -e "$PGPWD\n$PGPWD\n" | createuser -P trinventum"
#RUN su - postgres -c "createdb -O trinventum trinventum"
#RUN su - postgres -c "createlang plpgsql trinventum || true"

EXPOSE 5432
