#!/usr/bin/docker build --pull -t trinventum-db -f Dockerfile-trinventum-db .
# https://docs.docker.com/engine/reference/builder/

# https://hub.docker.com/_/postgres
FROM postgres:16

######################################################################
# NOTE: for professional use, you MUST add a permanent storage
######################################################################

RUN mkdir /docker-entrypoint-initdb.d || true
COPY docker/docker-db-create.sh /docker-entrypoint-initdb.d/
RUN chmod a+rx /docker-entrypoint-initdb.d/docker-db-create.sh
USER postgres

# "$POSTGRES_USER"?
#RUN su - postgres -c "echo -e "$PGPWD\n$PGPWD\n" | createuser -P trinventum"
#RUN su - postgres -c "createdb -O trinventum trinventum"
#RUN su - postgres -c "createlang plpgsql trinventum || true"

EXPOSE 5432
