# https://docs.docker.com/compose/compose-file/
#
# Trinventum Docker configuration - composer script
#
# Copyright (C) 2024-2026 Bogdan 'bogdro' Drozdowski, bogdro (at) users . sourceforge . net
#
# This file is part of Trinventum (Transaction and Inventory Unified Manager),
#  a software that helps manage an e-commerce business.
# Trinventum homepage: https://trinventum.sourceforge.io/
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

######################################################################
# NOTE: For professional use:
# - you MUST add a permanent storage
# - yum MUST change the passwords
######################################################################

services:
        #networks:
                #- trin_net
        trinventum_app:
                image: trinventum-app:latest
                hostname: trinventum-www
                container_name: trin-app
                depends_on:
                        - trinventum_db
                networks:
                        - trin_net
                ports:
                        - 80:80
                        - 443:443
        trinventum_db:
                image: trinventum-db:latest
                hostname: trinventum-db
                container_name: trin-db
                environment:
                        - POSTGRES_PASSWORD=postgres1234
                        - POSTGRES_DB=trinventum
                        - PGPWD=trinventum01
                networks:
                        - trin_net

networks:
        trin_net: {}
