#!/usr/bin/docker build --pull -t trinventum-app -f Dockerfile-trinventum-app .
#
# Trinventum Docker configuration - application container
#
# Copyright (C) 2024-2026 Bogdan 'bogdro' Drozdowski, bogdro (at) users . sourceforge . net
#
# This file is part of Trinventum (Transaction and Inventory Unified Manager),
#  a software that helps manage an e-commerce business.
# Trinventum homepage: https://trinventum.sourceforge.io/
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# https://docs.docker.com/engine/reference/builder/

# https://hub.docker.com/_/php/ ("-apache")
FROM php:apache

# webapp (NOTE: do NOT use "../webapp/*" - the subdirs don't get copied):
COPY webapp /var/www/html/
RUN chmod -R o+rX /var/www/html/* /var/www/html/.[a-z]*

# Apache configuration:
#RUN sed -i 's/#LoadModule mod_headers/LoadModule mod_headers/g' /etc/apache2/apache2.conf
RUN ln -sf /etc/apache2/mods-available/headers.load /etc/apache2/mods-enabled/headers.load

# PHP configuration:
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# PHP extensions:
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions pgsql

USER nobody
EXPOSE 80
